name: kubeaudit PR check

on:
  pull_request:

jobs:
  kubeaudit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download kubeaudit
        run: |
          curl -sLf -o kubeaudit.tar.gz https://github.com/Shopify/kubeaudit/releases/download/v0.14.2/kubeaudit_0.14.2_linux_amd64.tar.gz
          tar -zxvf kubeaudit.tar.gz
          chmod +x kubeaudit

      - name: Run kubeaudit and annotate PR
        run:  |
          ./kubeaudit all -f deployment.yml
